### ISSUE TITLE
problem with already existing jobs

### ISSUE THREAD

**Issue by letmp** [99soft/guartz#2]
hey!

I'm using guartz to run a job in my webapplication.
My webapp contains a method that creates the injector and a job for my class that implements quartz.Job.

The problem is, that the method can be called severall times ->
Error injecting method, org.quartz.ObjectAlreadyExistsException: Unable to store Job : 'DEFAULT.myJob', because one already exists with this identification.

Now i have three questions:
1) How can i catch the JobExecutionException from the execute(JobExecutionContext context) method in my main class where i created the injector?

2) Is there a way to test, if a job with a given name is already stored?

3) I have placed an @DisallowConcurrentExecution annotation in my class that implements quartz.Job. I hoped that this would  prevent to create several jobs for the same class. But this doesn't work. Why?

Thanks alot!

**Comment by nmwael** [comment]
quick answers:

2)
http://stackoverflow.com/questions/3799281/how-get-a-list-of-triggers-registered-to-a-quartz-scheduler
ask to get the Scheduler.class injected

3) problem is not concurrentexecution but that the names are the same. so either change the jobname or group in the annotation

**Comment by ginkel** [comment]
My patch from pull request #6 should solve the ObjectAlreadyExistsException (if you invoke updateExistingTrigger).

**Comment by simonetripodi** [comment]
I just applied pull request #6, release is coming! :)
